---
title: "R Notebook"
output: html_notebook
---
```{r  message=F, warning=F}
library(tidyverse)
library(readxl)
library(sf)
library(spData)
library(tmap)
```

```{r}
stations <- read_csv('Selected_stations_w_Data.csv') %>% 
  dplyr::select(Coast, station = Station, lat = Lat, lon = Lon, Train_test) %>% 
  drop_na()
stations_sf <- stations %>% st_as_sf(coords = c("lon", "lat"), crs = 4326)
```

```{r}
tmp <- world$geom[world$name_long == 'France'] %>% 
  st_cast('POLYGON') %>% st_cast("MULTIPOLYGON")

world$geom[world$name_long == 'France'] <- tmp[2:3]

tmp <- world$geom[world$name_long == 'Norway'] %>% 
  st_cast('POLYGON') %>% st_cast("MULTIPOLYGON")

world$geom[world$name_long == 'Norway'] <- tmp[4]
```


```{r}
map_regions <- data.frame(
  # Coast Name
  coast = c("NE_Atlantic_1",
            "NE_Atlantic_2",
            "NE_Pacific", 
            "Japan"),
  # Filtering condition for countries on the maps
  loc = c(rep('subregion %in% c("Western Europe", "Northern Europe", "Eastern Europe") & 
              !name_long %in% c("Russian Federation", "Iceland")', 2),
          'iso_a2 %in% c("US", "CA")',
          'name_long == "Japan"'))

maps <- NULL

create_map <- function(i){
  coast <- map_regions$coast[i]
  locs <- map_regions$loc[i]
  
  if (coast == 'NE_Pacific') {
    num_pos <- c("left", "bottom")} else
    {num_pos <- c("left", "top")}
  
  stations <- stations_sf %>% filter(Coast == coast) %>% rename("Use" = Train_test)
  
  num_stations <- nrow(stations)
  num_train <- nrow(stations %>% filter(`Use` == 'Train'))
  num_test <- nrow(stations %>% filter(`Use` == 'Test'))
  
  map <- world %>% 
    filter(!!rlang::parse_expr(locs)) %>% 
    tm_shape() + tm_borders() + tm_fill(col = "gray") + # Country Borders
    tm_shape(stations) + tm_dots(col='Use', size = .1, palette = c("blue", 'red')) + # Station Points 
    
    # Number of stations
    tm_credits(glue::glue('Num Training: {num_train} \n Num  Testing: {num_test}'),
               position=num_pos,
               fontface = 'bold',
               fontfamily = 'mono') + 
    # Layout
    tm_layout(legend.show = F,
              main.title = gsub('_', " ", coast), 
              main.title.position = "center" ,
              main.title.fontface = 'bold',
              main.title.fontfamily = "mono",
              bg.color = "lightcyan") 
  
  if (i == 4){ # Add legend for last plot
    map <- map + tm_layout(legend.show = T,
                          legend.frame = T,
                          legend.position = c("right", "bottom"),
                          legend.bg.alpha = 1,
                          legend.text.fontface = 'bold',
                          legend.title.fontface = 'bold',
                          legend.title.fontfamily = "mono",
                          legend.text.fontfamily = "mono")
    
  }
    map
  
}

maps <- purrr::map(1:4, create_map)


tm <- tmap_arrange(maps[[1]], maps[[2]], maps[[3]], maps[[4]], outer.margins = 0, ncol = 2)
tm

```

```{r }
tmap_save(tm, 'Selected_Stations_Map.png')
```




# TESTING




```{r}
map_regions <- data.frame(coast = c("NE Atlantic",
                                    "NE Pacific", 
                                    "Japan"),
                          loc = c('subregion %in% c("Western Europe", 
                                  "Northern Europe", 
                                  "Eastern Europe") & name_long != "Russian Federation"',
                                  'iso_a2 %in% c("US", "CA")',
                                  'name_long == "Japan"'),
                          leg = c(T, F, F))


maps <- NULL

create_map <- function(i){
  coast = map_regions$coast[i]
  locs = map_regions$loc[i]
  leg = map_regions$leg[i]
  
  if (coast == 'NE Atlantic') {
    cols = c("red", "blue")
    alpha =.6
    
  } else {
      
    cols = "red"
    alpha = 1
    
    }
    
    world %>% 
    filter(!!rlang::parse_expr(locs)) %>% 
    tm_shape() + tm_borders() + tm_fill(col = "gray") +
    tm_shape(stations_sf %>% filter(str_detect(Coast, coast))) + 
    tm_dots(col='Coast', size = .1, palette = cols, alpha = alpha)  + 
    tm_layout(legend.show = leg,
              main.title = coast, 
              main.title.position = "center" ,
              main.title.fontface = 'bold',
              legend.frame = T,
              legend.position = c("left", "top"),
              bg.color = "lightcyan",
              legend.bg.alpha = 1,
              legend.text.fontface = 'bold',
              legend.title.fontface = 'bold')
  
}

maps <- purrr::map(1:3, create_map)


tm <- tmap_arrange(maps[[2]], maps[[1]], maps[[3]], outer.margins = 0, ncol = 2)
tmap_save(tm, 'Selected_Stations_Map.png')
tm
```


```{r }
#tm_facets('continent') + 
  tm_shape(stations_sf) + 
  tm_dots(col='Coast', size = .2, palette = c('red','yellow', 'green', 'blue'))  + 
  tm_layout(legend.position = c("LEFT","BOTTOM"),
            legend.frame = TRUE) + 
  tm_shape(selected_areas) + tm_borders() + tm_fill() +
  tm_facets('subregion', free.coords =FALSE, free.scales=FALSE) 
```

```{r}
library(maps)
library(spDataLarge)
map("world", fill=TRUE, col="white", bg="gray", ylim=c(-60, 90), mar=c(0,0,0,0))
```

```{r}

ggplot() + 
  geom_sf(data = world, fill = NA, color = "gray45") + # borders of Scotland
  geom_sf(data = stations_sf, pch = 4, color = "red") + # the distilleries
  theme_void()
```


```{r}
country = 'Norway'
country = world %>% filter(name_long == country)
world %>% filter(subregion == 'Northern Europe') %>% 
  tm_shape() + tm_borders() + tm_fill() + 
 tm_shape(country) + tm_fill('blue')
```

